<?php

use App\Models\User;
use App\Models\WhatsappTemplate;
use App\Models\WhatsappTemplateComponent;
function sendBaseTemplate(){
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/105710885781444/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
        "messaging_product": "whatsapp",
        "to": "6281372823564",
        "type": "template",
        "template": {
            "name": "hello_world",
            "language": {
                "code": "en_US"
            }
        }
    }',
    CURLOPT_HTTPHEADER => array(
        'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz',
        'Content-Type: application/json'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
}

function sendOpenTicket($contact_no=null,$phone_number_id=null,$token=null)
{
    if($phone_number_id==null){
        $phone_number_id = '105710885781444';
    }
    if(@$token==null){
        $token ="EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz";
    }

    $curl = curl_init();

    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/'.$phone_number_id.'/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
        "messaging_product": "whatsapp",
        "to": "'.$contact_no.'",
        "type": "template",
        "template": {
            "name": "open_ticket",
            "language": {
                "code": "id"
            }
        }
    }',
    CURLOPT_HTTPHEADER => array(
        'Authorization: Bearer '.$token.'',
        'Content-Type: application/json'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
    return json_decode($response);
}

function sendTextTemplate($template=null,$contact=null,$phone_number_id=null,$token=null)
{

    if($phone_number_id==null){
        $phone_number_id = '105710885781444';
    }
    if(@$token==null){
        $token ="EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz";
    }
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/'.$phone_number_id.'/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
        "messaging_product": "whatsapp",
        "to": "'.$contact->phone_code.$contact->phone.'",
        "type": "template",
        "template": {
            "name": "'.$template->name.'",
            "language": {
                "code": "'.$template->language.'"
            }
        }
    }',
    CURLOPT_HTTPHEADER => array(
        'Authorization: Bearer '.$token.'',

        'Content-Type: application/json'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
    return json_decode($response);

}
function getTemplate(){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v15.0/101052632915714/message_templates');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    $headers = array();
    $headers[] = 'Authorization: Bearer EAAMmUBZBV7cIBAOErr9gofDCzZBzRQ3x1411ix4drwyxysAUXCepG6zqz54l0UN01LHy5NMPMVaFftfsxn54EJHVcpVWbXp8zX1xUzhM64Tcm8LuDSHc2Ur3iXj12wkilrXOOvYS2UStMseOZCpqB1g9j8h4jl2LfJyTvNJ2Lry9IgOhwWqFeY10jQch4xYmJ3j0x1FdwZDZD';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return json_decode($result);

}
function createTemplate($template){
        $whatsAppTemplate = WhatsappTemplate::find($template);
        $user = User::find($whatsAppTemplate->user_id);
        $ch = curl_init();
        // dd($whatsAppTemplate->content);
        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v16.0/'.$user->waba_id.'/message_templates');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $whatsAppTemplate->content);

        $headers = array();
        $headers[] = 'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return json_decode($result);
}

function createAdvanceTemplate(){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v15.0/{{WABA-ID}}/message_templates');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"category\": \"ISSUE_RESOLUTION\",\n    \"components\": [\n        {\n            \"type\": \"BODY\",\n            \"text\": \"message-text\"\n        }\n    ],\n    \"name\": \"hello_world_template\",\n    \"language\": \"en_US\"\n}");

    $headers = array();
    $headers[] = 'Authorization: Bearer {{System-User-Access-Token}}';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

}
function sendRegisterWa($dt){
    $user = User::find($dt);

    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/105710885781444/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
    "messaging_product": "whatsapp",
    "to": "'.$user->mobile_code.$user->mobile.'",
    "type": "template",
    "template": {
        "name": "next_registration_honey_gold",
        "language": {
            "code": "id",
            "policy": "deterministic"
        },
        "components": [
            {
                "type": "header",
                "parameters": [
                    {
                        "type": "image",
                        "image": {
                            "link": "https://i.ibb.co/tzN2vzL/Desain-tanpa-judul-7-removebg-preview-2.jpg"
                        }
                    }
                ]
            },
            {
                "type": "body",
                "parameters": [
                    {
                        "type": "text",
                        "text": "Member"
                    },
                    {
                        "type": "text",
                        "text": "'.$user->email.'"
                    },
                    {
                        "type": "text",
                        "text": "'.$user->password_confirmation.'"
                    }
                ]
            },
            {
                    "type": "button",
                    "sub_type" : "url",
                    "index": "1",
                    "parameters": [
                        {
                            "type": "text",
                            "text": "9rwnB8RbYmPF5t2Mn09x4h"
                        }
                    ]
                }
        ]
    }
    }',
    CURLOPT_HTTPHEADER => array(
        'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz',
        'Content-Type: application/json'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
    return json_decode($response,true);
}
function sendReplyWa(){
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/105710885781444/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
        "messaging_product": "whatsapp",
        "recipient_type": "individual",
        "to": "6281372823564",
        "type": "text",
        "text": {
            "preview_url": false,
            "body": "text-message-content"
        }
    }',
    CURLOPT_HTTPHEADER => array(
        'Content-Type: application/json',
        'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
    return json_decode($response,true);
}
function senBaseMessage($phone_number_id,$receiver,$preview_url,$text){
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/'.$phone_number_id.'/messages',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS =>'{
        "messaging_product": "whatsapp",
        "recipient_type": "individual",
        "to": "'.$receiver.'",
        "type": "text",
        "text": {
            "preview_url": "'.$preview_url.'",
            "body": "'.$text.'"
        }
    }',
    CURLOPT_HTTPHEADER => array(
        'Content-Type: application/json',
        'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz'
    ),
    ));

    $response = curl_exec($curl);
    curl_close($curl);

    // $curl = curl_init();
    // curl_setopt_array($curl, array(
    // CURLOPT_URL => 'https://graph.facebook.com/v16.0/105710885781444/messages',
    // CURLOPT_RETURNTRANSFER => true,
    // CURLOPT_ENCODING => '',
    // CURLOPT_MAXREDIRS => 10,
    // CURLOPT_TIMEOUT => 0,
    // CURLOPT_FOLLOWLOCATION => true,
    // CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    // CURLOPT_CUSTOMREQUEST => 'POST',
    // CURLOPT_POSTFIELDS =>'{
    //     "messaging_product": "whatsapp",
    //     "recipient_type": "individual",
    //     "to": "6281372823564",
    //     "type": "text",
    //     "text": {
    //         "preview_url": false,
    //         "body": "text-message-content"
    //     }
    // }',
    // CURLOPT_HTTPHEADER => array(
    //     'Content-Type: application/json',
    //     'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz'
    // ),
    // ));

    // $response = curl_exec($curl);

    // curl_close($curl);
    return json_decode($response);
}
/*
    POSSIBLE $logging VALUES
    BOOLEAN true -> log errors
    BOOLEAN false -> disable logging
*/
$logging = true;
/*
    POSSIBLE $checkNumbers VALUES
    BOOLEAN true -> check for numbers country code
    BOOLEAN false -> don't check for numbers country code
*/
$checkNumbers = true;

/*
    function that creates the array of nested values starting from the mautic payload.
    Nested arrays are created splitting values with the pipe symbol (|)
    you can use any symbol, take care to not use one char that can be used in texts values
*/
function creaArray(&$arr, $stringa, $valore) {
    $separator = "|";
    $chiavi = explode($separator, $stringa);

    foreach ($chiavi as $chiave) {
        $arr = &$arr[$chiave];
    }

    $arr = $valore;
}
function getPhoneWaba($waba_id){
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://graph.facebook.com/v16.0/'.$waba_id.'/phone_numbers',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
        'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz'
    ),
    ));

    $response = curl_exec($curl);

    curl_close($curl);
    return json_decode($response);
}
function getImageWa($mediaid){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v16.0/'.$mediaid.'/');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    $headers = array();
    $headers[] = 'Authorization: Bearer EAAMmUBZBV7cIBAKyPvBTZCJF8XLNZAjg1gXrfil0eT91u8XyeYwcbwBH8aY2ZA3hnTOW3Icr6ZBIpIjWBnkmROhClhZCcH9q01vGM6Vv005T69PMMXJ1oI8e9XNCNfRAx2HeCjoJoWURcONK2JoLPvC9gI3rAivbDz2IEUgYZBOrZBmKruLM8nyz';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $response = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return json_decode($response);

}
